<?php
/**
 * Phase 5 auth compatibility helper.
 *
 * During the beta database transition we need to support:
 * - modern PHP password_hash() rows
 * - plain legacy/dev rows
 * - guarded legacy-compatible local account rows generated by tools/create_local_account.py
 */

function bwps_auth_hash($plainValue) {
    return password_hash($plainValue, PASSWORD_DEFAULT);
}

function bwps_auth_is_modern_hash($storedValue) {
    if(!is_string($storedValue) || $storedValue === '') {
        return false;
    }

    $info = password_get_info($storedValue);
    return isset($info['algo']) && $info['algo'] !== 0;
}

function bwps_auth_legacy_scramble($username, $plainValue) {
    if(!is_string($username) || $username === '' || !is_string($plainValue)) {
        return '';
    }

    $key = '?F5-#b$8M*e!5eR4';
    $hash1 = sha1($plainValue, true);
    $hash1Sha = sha1($hash1, true);
    $mask = sha1($username . $plainValue . $key . $hash1Sha, true);
    $out = '';

    for($i = 0; $i < strlen($hash1); $i++) {
        $out .= chr(ord($hash1[$i]) ^ ord($mask[$i]));
    }

    return base64_encode($out);
}

function bwps_auth_verify($plainValue, $storedValue, $username = '') {
    if(!is_string($plainValue) || !is_string($storedValue)) {
        return false;
    }

    if(bwps_auth_is_modern_hash($storedValue)) {
        return password_verify($plainValue, $storedValue);
    }

    if(hash_equals($storedValue, $plainValue)) {
        return true;
    }

    if($username !== '') {
        return hash_equals($storedValue, bwps_auth_legacy_scramble($username, $plainValue));
    }

    return false;
}
?>