#!/usr/bin/env python3
"""Lightweight schema audit for legacy runtime-data design debt.

This tool does not change the database. It scans the generated schema and
reports patterns that should be reviewed before modernising runtime tables.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass, field
from pathlib import Path

CREATE_TABLE_RE = re.compile(
    r"CREATE\s+TABLE\s+`(?P<table>[^`]+)`\s*\((?P<body>.*?)\)\s*ENGINE=",
    re.IGNORECASE | re.DOTALL,
)

COLUMN_RE = re.compile(
    r"^\s*`(?P<name>[^`]+)`\s+(?P<type>[A-Za-z0-9()]+)(?P<rest>.*?)(?:,)?$",
    re.IGNORECASE,
)

TEXT_TYPES = ("text", "longtext", "mediumtext", "tinytext")
NAME_LINK_COLUMNS = {
    "ownername",
    "weevilname",
    "weevil",
    "username",
    "userid",
    "ownerid",
    "belongsto",
}
PACKED_LIST_COLUMNS = {
    "nameslist",
    "blocklist",
    "requestlist",
    "tasks",
    "progress",
    "wordscsv",
}
PACKED_DEFAULT_MARKERS = (",", "|", ":")
SENSITIVE_COLUMNS = {"password", "sessionkey", "loginkey", "loginip", "regip", "email"}


@dataclass
class Column:
    name: str
    type_name: str
    rest: str


@dataclass
class Table:
    name: str
    columns: list[Column] = field(default_factory=list)


def parse_schema(path: Path) -> list[Table]:
    content = path.read_text(encoding="utf-8", errors="replace")
    tables: list[Table] = []

    for table_match in CREATE_TABLE_RE.finditer(content):
        table = Table(name=table_match.group("table"))
        for raw_line in table_match.group("body").splitlines():
            column_match = COLUMN_RE.match(raw_line.rstrip())
            if not column_match:
                continue

            table.columns.append(
                Column(
                    name=column_match.group("name"),
                    type_name=column_match.group("type").lower(),
                    rest=column_match.group("rest"),
                )
            )
        tables.append(table)

    return tables


def column_default(rest: str) -> str | None:
    match = re.search(r"DEFAULT\s+('([^']*)'|[^\s,]+)", rest, re.IGNORECASE)
    if not match:
        return None
    return match.group(1).strip("'")


def audit_table(table: Table) -> list[str]:
    notes: list[str] = []
    lowered_table = table.name.lower()

    if "-" in table.name:
        notes.append("hyphenated table name; awkward to query and easy to mishandle without backticks")

    for column in table.columns:
        lowered_column = column.name.lower()
        default = column_default(column.rest)

        if column.name.isdigit():
            notes.append(f"numeric column name `{column.name}`; awkward to query and probably a legacy export smell")

        if lowered_column in NAME_LINK_COLUMNS:
            notes.append(f"`{column.name}` appears to link rows by name/string rather than stable numeric user id")

        if lowered_column in PACKED_LIST_COLUMNS:
            notes.append(f"`{column.name}` looks like packed list/progress data that should be reviewed for normalisation")

        if lowered_column in SENSITIVE_COLUMNS:
            notes.append(f"`{column.name}` stores account/session data; keep out of default seeds and review auth handling")

        if any(column.type_name.startswith(text_type) for text_type in TEXT_TYPES):
            notes.append(f"`{column.name}` uses {column.type_name}; check if it blocks indexing/searching")

        if default and any(marker in default for marker in PACKED_DEFAULT_MARKERS):
            notes.append(f"`{column.name}` default `{default}` looks like packed/encoded runtime state")

    if lowered_table in {"buddylist", "taskscompletedbyusers", "users", "nest", "nestinfo"}:
        notes.append("runtime bootstrap table; do not redesign directly until compatibility behaviour is mapped")

    return sorted(set(notes))


def render_markdown(tables: list[Table]) -> str:
    lines = [
        "# Runtime Schema Debt Report",
        "",
        "Generated by `tools/audit_schema_debt.py`.",
        "",
        "This report is a review aid only. It does not mean every flagged table should be changed immediately.",
        "",
    ]

    flagged = 0
    for table in tables:
        notes = audit_table(table)
        if not notes:
            continue

        flagged += 1
        lines.append(f"## `{table.name}`")
        lines.append("")
        for note in notes:
            lines.append(f"- {note}")
        lines.append("")

    lines.insert(4, f"Flagged tables: {flagged}")
    lines.insert(5, "")
    return "\n".join(lines).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit legacy schema for runtime-data design debt.")
    parser.add_argument(
        "--schema",
        default="database/schema/001_base_schema.sql",
        help="Path to schema SQL file to audit.",
    )
    parser.add_argument(
        "--output",
        help="Optional markdown output path. If omitted, the report is printed to stdout.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    schema_path = Path(args.schema)
    tables = parse_schema(schema_path)
    report = render_markdown(tables)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report, encoding="utf-8")
        print(f"Wrote schema debt report to {output_path}")
    else:
        print(report, end="")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
