#!/usr/bin/env python3
"""Scan PHP/JS runtime files for database table references.

This is a read-only audit helper. It does not connect to MySQL and does not
change runtime code.
"""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path

RUNTIME_ROOTS = [
    Path("game-full"),
    Path("server"),
]

SOURCE_SUFFIXES = {".php", ".js"}

TABLE_PATTERNS = [
    re.compile(r"\bFROM\s+`?([A-Za-z0-9_\-]+)`?", re.IGNORECASE),
    re.compile(r"\bJOIN\s+`?([A-Za-z0-9_\-]+)`?", re.IGNORECASE),
    re.compile(r"\bUPDATE\s+`?([A-Za-z0-9_\-]+)`?", re.IGNORECASE),
    re.compile(r"\bINTO\s+`?([A-Za-z0-9_\-]+)`?", re.IGNORECASE),
    re.compile(r"\bDELETE\s+FROM\s+`?([A-Za-z0-9_\-]+)`?", re.IGNORECASE),
]

RUNTIME_SENSITIVE_TABLES = {
    "users",
    "buddylist",
    "buddyalerts",
    "nest",
    "nestinfo",
    "weevilitems",
    "weevilhats",
    "gardeninventory",
    "taskscompletedbyusers",
    "achievementcounters",
    "achievementscompleted",
    "crossworduserprogress",
    "wordsearchuserprogress",
    "singleplayergames_stats",
    "leaderboardhighscores",
    "multiplayergames",
    "pets",
    "petacquiredskills",
    "redeemedcodes",
    "tycoonbusinesses",
}

BOOT_CRITICAL_TABLES = {
    "users",
    "buddylist",
}


def iter_source_files(paths: list[Path]) -> list[Path]:
    files: list[Path] = []
    for root in paths:
        if not root.exists():
            continue
        if root.is_file() and root.suffix.lower() in SOURCE_SUFFIXES:
            files.append(root)
            continue
        if root.is_dir():
            for path in root.rglob("*"):
                if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
                    files.append(path)
    return sorted(files)


def scan_file(path: Path) -> set[str]:
    content = path.read_text(encoding="utf-8", errors="replace")
    tables: set[str] = set()
    for pattern in TABLE_PATTERNS:
        for match in pattern.finditer(content):
            tables.add(match.group(1))
    return tables


def render_report(table_to_files: dict[str, set[Path]]) -> str:
    lines: list[str] = [
        "# Runtime Table Usage Audit",
        "",
        "Generated by `tools/audit_runtime_table_usage.py`.",
        "",
        "This is a source-code reference scan. It is a review aid, not a full SQL parser.",
        "",
        "## Summary",
        "",
        f"Tables referenced: {len(table_to_files)}",
        "",
    ]

    boot_hits = sorted(table for table in table_to_files if table.lower() in BOOT_CRITICAL_TABLES)
    runtime_hits = sorted(table for table in table_to_files if table.lower() in RUNTIME_SENSITIVE_TABLES)

    lines.extend([
        "## Boot-critical table references",
        "",
    ])
    if boot_hits:
        for table in boot_hits:
            lines.append(f"- `{table}`")
    else:
        lines.append("No boot-critical tables found by the scanner.")
    lines.append("")

    lines.extend([
        "## Runtime/player-state table references",
        "",
    ])
    if runtime_hits:
        for table in runtime_hits:
            lines.append(f"- `{table}`")
    else:
        lines.append("No runtime/player-state tables found by the scanner.")
    lines.append("")

    lines.extend([
        "## Table to file map",
        "",
    ])

    for table in sorted(table_to_files, key=str.lower):
        lines.append(f"### `{table}`")
        lines.append("")
        for path in sorted(table_to_files[table], key=lambda p: str(p).lower()):
            lines.append(f"- `{path.as_posix()}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Scan runtime source files for SQL table references.")
    parser.add_argument(
        "paths",
        nargs="*",
        default=[str(path) for path in RUNTIME_ROOTS],
        help="Files/directories to scan. Defaults to game-full and server.",
    )
    parser.add_argument("--output", help="Optional markdown output path.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    files = iter_source_files([Path(path) for path in args.paths])
    table_to_files: dict[str, set[Path]] = defaultdict(set)

    for file_path in files:
        for table in scan_file(file_path):
            table_to_files[table].add(file_path)

    report = render_report(table_to_files)
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report, encoding="utf-8")
        print(f"Wrote runtime table usage audit to {output_path}")
    else:
        print(report, end="")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
