#!/usr/bin/env python3
"""Scan PHP/JS runtime files for database table references.

This is a read-only audit helper. It does not connect to MySQL and does not
change runtime code.
"""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

RUNTIME_ROOTS = [
    Path("game-full"),
    Path("server"),
]

SOURCE_SUFFIXES = {".php", ".js"}

TABLE_PATTERNS = [
    ("FROM", re.compile(r"\bFROM\s+`?([A-Za-z0-9_\-]+)`?", re.IGNORECASE)),
    ("JOIN", re.compile(r"\bJOIN\s+`?([A-Za-z0-9_\-]+)`?", re.IGNORECASE)),
    ("UPDATE", re.compile(r"\bUPDATE\s+`?([A-Za-z0-9_\-]+)`?", re.IGNORECASE)),
    ("INSERT", re.compile(r"\bINSERT\s+INTO\s+`?([A-Za-z0-9_\-]+)`?", re.IGNORECASE)),
    ("DELETE", re.compile(r"\bDELETE\s+FROM\s+`?([A-Za-z0-9_\-]+)`?", re.IGNORECASE)),
]

RUNTIME_SENSITIVE_TABLES = {
    "users",
    "buddylist",
    "buddyalerts",
    "nest",
    "nestinfo",
    "weevilitems",
    "weevilhats",
    "gardeninventory",
    "taskscompletedbyusers",
    "achievementcounters",
    "achievementscompleted",
    "crossworduserprogress",
    "wordsearchuserprogress",
    "singleplayergames_stats",
    "leaderboardhighscores",
    "multiplayergames",
    "pets",
    "petacquiredskills",
    "redeemedcodes",
    "tycoonbusinesses",
}

BOOT_CRITICAL_TABLES = {
    "users",
    "buddylist",
}


@dataclass(frozen=True, order=True)
class TableHit:
    path: Path
    line_number: int
    operation: str


def iter_source_files(paths: list[Path]) -> list[Path]:
    files: list[Path] = []
    for root in paths:
        if not root.exists():
            continue
        if root.is_file() and root.suffix.lower() in SOURCE_SUFFIXES:
            files.append(root)
            continue
        if root.is_dir():
            for path in root.rglob("*"):
                if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES:
                    files.append(path)
    return sorted(files)


def scan_file(path: Path) -> dict[str, set[TableHit]]:
    table_hits: dict[str, set[TableHit]] = defaultdict(set)

    for line_number, line in enumerate(path.read_text(encoding="utf-8", errors="replace").splitlines(), start=1):
        for operation, pattern in TABLE_PATTERNS:
            for match in pattern.finditer(line):
                table = match.group(1)
                table_hits[table].add(TableHit(path=path, line_number=line_number, operation=operation))

    return table_hits


def merge_hits(destination: dict[str, set[TableHit]], source: dict[str, set[TableHit]]) -> None:
    for table, hits in source.items():
        destination[table].update(hits)


def render_report(table_to_hits: dict[str, set[TableHit]]) -> str:
    lines: list[str] = [
        "# Runtime Table Usage Audit",
        "",
        "Generated by `tools/audit_runtime_table_usage.py`.",
        "",
        "This is a source-code reference scan. It is a review aid, not a full SQL parser.",
        "",
        "## Summary",
        "",
        f"Tables referenced: {len(table_to_hits)}",
        f"Reference hits: {sum(len(hits) for hits in table_to_hits.values())}",
        "",
    ]

    boot_hits = sorted(table for table in table_to_hits if table.lower() in BOOT_CRITICAL_TABLES)
    runtime_hits = sorted(table for table in table_to_hits if table.lower() in RUNTIME_SENSITIVE_TABLES)

    lines.extend([
        "## Boot-critical table references",
        "",
    ])
    if boot_hits:
        for table in boot_hits:
            lines.append(f"- `{table}` ({len(table_to_hits[table])} hit(s))")
    else:
        lines.append("No boot-critical tables found by the scanner.")
    lines.append("")

    lines.extend([
        "## Runtime/player-state table references",
        "",
    ])
    if runtime_hits:
        for table in runtime_hits:
            lines.append(f"- `{table}` ({len(table_to_hits[table])} hit(s))")
    else:
        lines.append("No runtime/player-state tables found by the scanner.")
    lines.append("")

    lines.extend([
        "## Table to file map",
        "",
    ])

    for table in sorted(table_to_hits, key=str.lower):
        lines.append(f"### `{table}`")
        lines.append("")
        for hit in sorted(table_to_hits[table]):
            lines.append(f"- `{hit.path.as_posix()}:{hit.line_number}` ({hit.operation})")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Scan runtime source files for SQL table references.")
    parser.add_argument(
        "paths",
        nargs="*",
        default=[str(path) for path in RUNTIME_ROOTS],
        help="Files/directories to scan. Defaults to game-full and server.",
    )
    parser.add_argument("--output", help="Optional markdown output path.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    files = iter_source_files([Path(path) for path in args.paths])
    table_to_hits: dict[str, set[TableHit]] = defaultdict(set)

    for file_path in files:
        merge_hits(table_to_hits, scan_file(file_path))

    report = render_report(table_to_hits)
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report, encoding="utf-8")
        print(f"Wrote runtime table usage audit to {output_path}")
    else:
        print(report, end="")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
