#!/usr/bin/env python3
"""Check legacy auth files for Phase 5 migration readiness.

This is a read-only scanner. It does not alter runtime code and does not
connect to the database.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

DEFAULT_FILES = [
    Path("game-full/login/login.php"),
    Path("game-full/register/create-new-weevil.php"),
]


@dataclass(frozen=True)
class Finding:
    path: Path
    line_number: int
    severity: str
    message: str


def scan_file(path: Path) -> list[Finding]:
    findings: list[Finding] = []
    if not path.exists():
        findings.append(Finding(path, 0, "error", "expected auth file is missing"))
        return findings

    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    for line_number, line in enumerate(lines, start=1):
        compact = line.replace(" ", "").replace("\t", "")
        lower_line = line.lower()

        if "password" in lower_line and "==" in line:
            findings.append(
                Finding(
                    path,
                    line_number,
                    "error",
                    "direct credential equality check still present; replace with compatibility helper",
                )
            )

        if "insert into" in lower_line and "users" in lower_line and "password" in lower_line:
            findings.append(
                Finding(
                    path,
                    line_number,
                    "warning",
                    "user creation writes credential field; ensure new local accounts use the compatibility helper",
                )
            )

        if "bind_param" in lower_line and "password" in compact.lower():
            findings.append(
                Finding(
                    path,
                    line_number,
                    "warning",
                    "credential value is bound into SQL; confirm it is transformed before storage",
                )
            )

    return findings


def render_markdown(findings: list[Finding]) -> str:
    lines = [
        "# Auth Readiness Report",
        "",
        "Generated by `tools/check_auth_readiness.py`.",
        "",
        "This report is a Phase 5 review aid before runtime auth changes.",
        "",
        "## Findings",
        "",
    ]

    if not findings:
        lines.append("No readiness findings detected.")
        return "\n".join(lines) + "\n"

    for finding in findings:
        location = finding.path.as_posix()
        if finding.line_number:
            location = f"{location}:{finding.line_number}"
        lines.append(f"- **{finding.severity.upper()}** `{location}` - {finding.message}")

    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Check auth files for Phase 5 migration readiness.")
    parser.add_argument(
        "paths",
        nargs="*",
        default=[str(path) for path in DEFAULT_FILES],
        help="Auth files to scan.",
    )
    parser.add_argument("--output", help="Optional markdown output path.")
    parser.add_argument(
        "--fail-on-error",
        action="store_true",
        help="Exit with status 1 if error findings are detected.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    findings: list[Finding] = []
    for path_text in args.paths:
        findings.extend(scan_file(Path(path_text)))

    report = render_markdown(findings)
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report, encoding="utf-8")
        print(f"Wrote auth readiness report to {output_path}")
    else:
        print(report, end="")

    if args.fail_on_error and any(finding.severity == "error" for finding in findings):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
