#!/usr/bin/env python3
"""Check runtime auth files for Phase 5 migration readiness.

This is a read-only scanner. It does not alter runtime code and does not
connect to the database.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

DEFAULT_FILES = [
    Path("game-full/login/login.php"),
    Path("game-full/register/create-new-weevil.php"),
]


@dataclass(frozen=True)
class Finding:
    path: Path
    line_number: int
    severity: str
    message: str


def has_helper_include(text: str) -> bool:
    return "auth_compat.php" in text


def has_helper_verify(text: str) -> bool:
    return "bwps_auth_verify(" in text


def has_helper_hash(text: str) -> bool:
    return "bwps_auth_hash(" in text


def is_direct_credential_comparison(line: str) -> bool:
    lower_line = line.lower()
    compact = line.replace(" ", "").replace("\t", "").lower()

    if "password" not in lower_line:
        return False

    if "bwps_auth_verify(" in lower_line:
        return False

    return "==" in line or "===" in line or "!= " in line or "!==" in line or "!=" in compact


def is_raw_credential_binding(line: str) -> bool:
    compact = line.replace(" ", "").replace("\t", "").lower()
    if "bind_param" not in compact:
        return False

    return "$password" in compact and "$storedcredential" not in compact


def scan_file(path: Path) -> list[Finding]:
    findings: list[Finding] = []
    if not path.exists():
        findings.append(Finding(path, 0, "error", "expected auth file is missing"))
        return findings

    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    lower_path = path.as_posix().lower()

    if lower_path.endswith("login.php"):
        if not has_helper_include(text):
            findings.append(Finding(path, 0, "error", "login does not include the auth compatibility helper"))
        if not has_helper_verify(text):
            findings.append(Finding(path, 0, "error", "login does not use the helper verifier"))

    if lower_path.endswith("create-new-weevil.php"):
        if not has_helper_include(text):
            findings.append(Finding(path, 0, "error", "registration does not include the auth compatibility helper"))
        if not has_helper_hash(text):
            findings.append(Finding(path, 0, "error", "registration does not create a helper-hashed stored credential"))

    for line_number, line in enumerate(lines, start=1):
        lower_line = line.lower()

        if is_direct_credential_comparison(line):
            findings.append(
                Finding(
                    path,
                    line_number,
                    "error",
                    "direct credential comparison still present; use the compatibility helper",
                )
            )

        if is_raw_credential_binding(line):
            findings.append(
                Finding(
                    path,
                    line_number,
                    "error",
                    "raw submitted credential is still bound into SQL; bind the helper-generated stored credential instead",
                )
            )

        if "insert into" in lower_line and "users" in lower_line and "password" in lower_line:
            if lower_path.endswith("create-new-weevil.php") and has_helper_hash(text):
                continue
            findings.append(
                Finding(
                    path,
                    line_number,
                    "warning",
                    "user creation writes credential field; confirm helper-generated storage is used",
                )
            )

    return findings


def render_markdown(findings: list[Finding]) -> str:
    lines = [
        "# Auth Readiness Report",
        "",
        "Generated by `tools/check_auth_readiness.py`.",
        "",
        "This report is a Phase 5 review aid for runtime auth changes.",
        "",
        "## Findings",
        "",
    ]

    if not findings:
        lines.append("No readiness findings detected.")
        return "\n".join(lines) + "\n"

    for finding in findings:
        location = finding.path.as_posix()
        if finding.line_number:
            location = f"{location}:{finding.line_number}"
        lines.append(f"- **{finding.severity.upper()}** `{location}` - {finding.message}")

    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Check auth files for Phase 5 migration readiness.")
    parser.add_argument(
        "paths",
        nargs="*",
        default=[str(path) for path in DEFAULT_FILES],
        help="Auth files to scan.",
    )
    parser.add_argument("--output", help="Optional markdown output path.")
    parser.add_argument(
        "--fail-on-error",
        action="store_true",
        help="Exit with status 1 if error findings are detected.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    findings: list[Finding] = []
    for path_text in args.paths:
        findings.extend(scan_file(Path(path_text)))

    report = render_markdown(findings)
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report, encoding="utf-8")
        print(f"Wrote auth readiness report to {output_path}")
    else:
        print(report, end="")

    if args.fail_on_error and any(finding.severity == "error" for finding in findings):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
